### ISSUE TITLE
Start payment from a Quote

### ISSUE THREAD

**Issue by gasparez15** [cytech/FusionInvoice-FOSS#1]
Hi cytech,
first of all I would like to thank you, in fact, thanks to your repository we were able to update our FusioniNvoice from the 2017-9 version to 2018-8.
Now we have a dilemma: upgrade the system to your version 4.0.2 or switch to InvoicePlane 2.0.1 alpha ...
In addition we have an opportunity to present you: we would need the possibility of being able to directly pay a quote with (Paypal and Stripe) and then turn the quote into an invoice.
If you are interested we are willing to sponsor this development

**Comment by cytech** [comment]
I do not know the status or plans of Invoice Plane. Mostly this repo is here to support my own existing customers who use FusionInvoice and the addons i had created for it.
As far as the quote payment goes, in fusioninvoicefoss-system-settings-quote tab, you can turn on "Automatically Convert Quote to Invoice When Client Approves:"
Then the workflow would be  - Create quote, client accesses the quote and approves it, the quote is automatically converted to an invoice which the client can then pay.

**Comment by gasparez15** [comment]
Hi Cytech,
unfortunately that is not good for us, because once an invoice is made this invoice is automatically transmitted to the revenue agency. If the customer does not complete the payment we find ourselves paying taxes on invoices that could not be paid (this is a very serious problem). So our idea is to make the quate payable directly, if the customer completes the payment we turn the quote into an invoice already paid.
This development has considerable value for us

**Comment by cytech** [comment]
the amount of changes involved to allow payment of a quote break the current workflow standard,
so I do not see it happening at this time.

**Comment by gasparez15** [comment]
Ok Cytech,
thanks for your honest answer, however, 
just because you know an addon that allows us to perform this process for us is worth $ 1000

**Comment by cytech** [comment]
understood
i will keep it in mind
