### ISSUE TITLE
Development status

### ISSUE THREAD

**Issue by nickbe** [cytech/FusionInvoice-FOSS#3]
Is this project still actively developed? If so, may we contribute with ideas and/or work?

**Comment by cytech** [comment]
Yes it is.
Feel free to fork it and i'll look at PR's\
thanx

**Comment by nickbe** [comment]
Is there some license information for this was open sourced version somewhere?

**Comment by cytech** [comment]
well, now i am not sure.
In May 2018 the original developer announced that FusionInvoice was closing business operations.
At that point (in the announcement) he said "If any of you would like to maintain the project as FOSS, please feel free."
Yesterday I received an email saying development is restarting and  it "is not open source after all."
so I would not do anything with the repo as it may disappear soon.
thanx

**Comment by nickbe** [comment]
Well if he said "At that point (in the announcement) he said "If any of you would like to maintain the project as FOSS, please feel free." then there's usually no turning back.

Otherwise open source authors would be able to change the rules at will - which they can't.
If I declare a project as "free for open source community" then that's it.

I really hate it when people think they don't have to stick to their word.

**Comment by cytech** [comment]
after discussion with the original developer, it was agreed that it was publicly stated that the software could go FOSS.
We agreed to a name change of this repo to differentiate the products.

**Comment by nickbe** [comment]
Ok. I'll get back to you in the next few days because we would like to help with improving the system.
Thanks!
